### ISSUE TITLE
ES6 Modules port

### ISSUE THREAD

**Issue by VladimirCores** [PureMVC/puremvc-js-multicore-framework#6]
It would be good to have update to modern JS syntax.

Thank,
Vladimir

**Comment by cliffhall** [comment]
This is true, Vladimir. While it does work fine as is on pretty much every browser in the universe at the moment, it took a lot of effort to make that happen back when it was originally ported and it still required helpers to make it OOPy. It is less than optimal.

A refactor to ES6 using classes would now be perfectly reasonable and is well overdue. I will look into doing that update myself.

Cheers,
-=Cliff>

**Comment by saadshams** [comment]
port upgraded to use ES6 classes.
