### ISSUE TITLE
Minified version missing a few methods

### ISSUE THREAD

**Issue by dominicosavio** [PureMVC/puremvc-js-multicore-framework#7]
Minified version doesn't have the following methods: puremvc.declare and puremvc.define

//Declare a namespace and optionally make an Object the referent of that namespace.
puremvc.declare( string string, [Object object], [Object scope] ) : Object

//Define a new classlet. 
puremvc.define( [Object classinfo], [Object traits], [Object staitcTraits] ) : Function

**Comment by saadshams** [comment]
An upgrade is available using ES6 classes.
